### ISSUE TITLE
Is anyone using this at scale?

### ISSUE THREAD

**Issue by benrolfe** [cyrildewit/laravel-page-view-counter#24]
I'm about to add this package to my project, but wondered how this would scale with large numbers of views? Do queries become very slow when thousands of records have been saved to the database?

Anyone have experience of using this with MySQL?

**Comment by cyrildewit** [comment]
I actually have no idea if this package is used in a large project 😬. I am interested in there feedback :D.

No, this package is using the [aggregate count method](https://laravel.com/docs/5.5/queries#aggregates) to count the total number of page views. It will use SQL's count method instead of retrieving all the records and then count them.

-------------------------------
**[Off topic but still useful to know]**

I'm currently working on v1.0 and wanted to let know that it will change a lot. I'm getting rid of all the attributes that are appended to your Eloquent model. It's kinda messy to have 14 attributes with same value. This gives you the option if you want to append it. All these attributes will be replaced with a few methods.

A little example:
```php
// Instead of this
$article->page_views               // total page views
$article->page_views_formatted     // total page views formatted

// It will become
$article->getPageViews()           // total page views
```
As you can see, the formatting functionality will be removed because it's out of the scope of this package. If you still want to format it, you need to use PHP's  `number_format()` function. It's maybe useful to create a simple helper function.
