### ISSUE TITLE
[Suggestion] Increment Visit Rather than creating a new entry

### ISSUE THREAD

**Issue by Teranode** [cyrildewit/laravel-page-view-counter#45]
Rather than flooding the database with new visit entries why not create a new column that gets incremented, every time someone with the same IP visits the site, the total pageviews would just count sum of all the increments all ips have for that model and the unique views would count just for that row for each visited IP. This way you wont end up with a completely flooded database filled with records.

**Comment by cyrildewit** [comment]
Hi @Teranode! Thanks for the suggestion!

I have thought a lot about what the best solution for this is. The reason why I save each visit separately, is because I want to be able to look back in the history. Let's say I want to know how many people have visited this post between January 1 2017 and March 1 2017. I could simply count this by using `$model->getVisitsCountBetween($sinceDate, $uptoDate));`. If I just incremented a collumn on the model's table, I could't do this :/.

My current solution is caching these result for a while. YouTube does this too (I think). When you refresh the page, you still see the same number of views. So that means they are not counting it on each request.

I am currently working on this in the `v2.0.x` branch. Another improvement was adding the possibility to queue the process of storing the visits.

What I could do is adding another option to the config file where you can tell the package if it needs to save each visit seperately or if it should increment a collumn on the model, but once you have choosed for the second option, there is no coming back.

**Comment by cyrildewit** [comment]
> What I could do is adding another option to the config file where you can tell the package if it needs to save each visit seperately or if it should increment a collumn on the model...

Do you think this would be a must for people? @Teranode

**Comment by Teranode** [comment]
Depends on what kind of application they're running, but in the long-run its a good option for large applications. I wish there was some easier way of working this without the large overhead of rows.

**Comment by cyrildewit** [comment]
If people only want to have a simple page view counter, they don't need this package.
They can simply add a collumn to their models and increment it on each pageview.

Thanks for the suggestion! I am closing this issue for now, because of the above reason.
