### ISSUE TITLE
Eager Loading with it

### ISSUE THREAD

**Issue by kubands** [cyrildewit/laravel-page-view-counter#62]
Hey, can you give me a advice, how make Eager Loading on my model with it?

**Comment by cyrildewit** [comment]
What do you want to eager load?

**Comment by kubands** [comment]
On my model Article, Course and User. Because i want to show user, how many viewers they have on all courses.

**Comment by cyrildewit** [comment]
Whoops... I answered this yesterday, but it looks like that I forgot to click on comment.

Eager loading the `views` relationship will only make it slower, because the counting is done with SQL's aggregrate methods.

**Comment by kubands** [comment]
Hm.. what do you recommend me? I have above 100 request on view. I want to collect unique views for user articles, courses and author page.

**Comment by cyrildewit** [comment]
Caching the views count value for a while can make the application faster, that's why I added caching functionality to `v2.0.0`, but this version will isn't released yet. I have planned it on [May 28, 2018](https://github.com/cyrildewit/laravel-page-view-counter/milestone/1).

How long does it take to the load the page at the moment?

**Comment by kubands** [comment]
above 1 sec and still rise

**Comment by cyrildewit** [comment]
Is it a really important requirement to make the page load faster at the moment? Because I can release a betá version of v2 so you can use it. You will need to upgrade the application of course.

If you have the time, you could test version 2 and check if it fixes the speed problem for you.

I think just changing the version number to `dev-2.0.0`  in composer.json would do the job. I suggest you to create a new branch, so you can rollback the changes.

https://github.com/cyrildewit/laravel-page-view-counter/tree/2.0
https://github.com/cyrildewit/laravel-page-view-counter/blob/2.0/UPGRADING.md
