### ISSUE TITLE
sortBy with paginate

### ISSUE THREAD

**Issue by zymawy** [cyrildewit/laravel-page-view-counter#65]
- Laravel Page View Counter Version: ^1.0
- Laravel Version: 5.6.*
- PHP Version:7.1.9
- Database Driver & Version:mysql 

### Description:
It seems that `sortBy` not working properly with `paginate`

when trying this 

```php
        $scholarships  = Scholarship::with(
            'city.country'
        )->paginate(12)->sortBy('page_views');     
```
it throwing `method not exist exception`
```php
ErrorException Method Illuminate\Database\Eloquent\Collection::links does not exist. 
```

**Comment by cyrildewit** [comment]
Hey @zymawy,

First I want to thank you for using this package.

The `sortBy` method is provided by Laravel collections, so this issue is not related to this package.

I don't recommend the `sortBy` method anymore. It's much slower than using plain SQL. I added a faster solution to `v2`. I think we can only achieve this with a left join, but you could try the following:

```php
$scholarships = Scholarship::with()->orderBy('page_views')->paginate(12);
```

Otherwise you will have to use a left join. Take a look at the following [code](https://github.com/cyrildewit/laravel-page-view-counter/blob/2.0/src/ViewableService.php#L248) that I added to `v2`. You can directly use this piece of code on your queries or create a scope (cleaner approach). If you decide to create a scope [this link](https://github.com/cyrildewit/laravel-page-view-counter/blob/2.0/src/Viewable.php#L98) might also be useful.

I hope this information will help you fixing your issue. If you still have any questions, you can comment on this issue. I will close this issue for now.

I also don't have any plans to add this feature to `v1.0`. The next major version, which contains this feature, will soon be released. May 28, 201 to be precise.

Regards,
Cyril
